# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c19321743333009b83042d00565a4e22d72beba3d377ab6ed1eed9b5322c97bdc2bd843ebac9283833f6c0d0b4fa0d3e11513c4f2793d0612018f1c19e7b695f

test:
  secret_key_base: 33349ec6d32bfc2cf1f1c41b69c9f9ca72ed321d101657f68a39d69541ea238affe15a9641503ab8c3f6b52799d428ce5475ec5a1e5c42654b9afad0234b7d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
